/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pds.labs.pharmacysystemnetbeans;

import javax.swing.ImageIcon;
import javax.swing.UIManager;

/**
 *
 * @author andre
 */
public class PharmacyWindows extends javax.swing.JFrame {

    private ImageIcon INFO_ICON;
    private ImageIcon CHECK_ICON;
    /**
     * Creates new form PharmacyWindows
     */
    public PharmacyWindows() {
        initComponents();
        //System.out.println(getClass().getResource("/resources/info.jpg"));
        //INFO_ICON  = new ImageIcon(getClass().getResource("/resources/info.jpg"));
        //CHECK_ICON = new ImageIcon(getClass().getResource("/resources/check.jpg"));
        btnGroupProviders.add(rdbtnProvider1);
        btnGroupProviders.add(rdbtProvider2);
        btnGroupProviders.add(rdbtnProvider3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupProviders = new javax.swing.ButtonGroup();
        pnlPharmacy = new javax.swing.JPanel();
        lblMedicineName = new javax.swing.JLabel();
        lblItemNumber = new javax.swing.JLabel();
        lblProvider = new javax.swing.JLabel();
        txtMedicineName = new javax.swing.JTextField();
        txtNumberItem = new javax.swing.JSpinner();
        rdbtnProvider1 = new javax.swing.JRadioButton();
        rdbtProvider2 = new javax.swing.JRadioButton();
        rdbtnProvider3 = new javax.swing.JRadioButton();
        lblTypeMedicine = new javax.swing.JLabel();
        cmbTypeMedicine = new javax.swing.JComboBox<>();
        lblAddress = new javax.swing.JLabel();
        chckMainAddress = new javax.swing.JCheckBox();
        chkAlternativeAddress = new javax.swing.JCheckBox();
        lblAddressCheck = new javax.swing.JLabel();
        lblMedicineNameCheck = new javax.swing.JLabel();
        lblItemNumberCheck = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlPharmacy.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMedicineName.setText("Nombre del pedido:");
        pnlPharmacy.add(lblMedicineName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 131, -1));

        lblItemNumber.setText("Cantidad del producto:");
        pnlPharmacy.add(lblItemNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 131, -1));

        lblProvider.setText("Seleccione el distribuidor:");
        pnlPharmacy.add(lblProvider, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 115, 131, -1));

        txtMedicineName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMedicineNameKeyReleased(evt);
            }
        });
        pnlPharmacy.add(txtMedicineName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 122, -1));

        txtNumberItem.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtNumberItemStateChanged(evt);
            }
        });
        pnlPharmacy.add(txtNumberItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 122, -1));

        rdbtnProvider1.setSelected(true);
        rdbtnProvider1.setText("Cofarma");
        rdbtnProvider1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnProvider1ActionPerformed(evt);
            }
        });
        pnlPharmacy.add(rdbtnProvider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 111, -1, -1));

        rdbtProvider2.setText("Empsephar");
        pnlPharmacy.add(rdbtProvider2, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 134, -1, -1));

        rdbtnProvider3.setText("Cemefar");
        pnlPharmacy.add(rdbtnProvider3, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 157, -1, -1));

        lblTypeMedicine.setText("Tipo de medicamento:");
        pnlPharmacy.add(lblTypeMedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 35, -1, -1));

        cmbTypeMedicine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Analgésico", "Analéptico", "Anestésico", "Antiácido", "Antidepresivo ", "Antibióticos" }));
        pnlPharmacy.add(cmbTypeMedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 32, 170, -1));

        lblAddress.setText("Entrega en sucursal:");
        pnlPharmacy.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 74, 100, -1));

        chckMainAddress.setText("Principal");
        chckMainAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckMainAddressActionPerformed(evt);
            }
        });
        pnlPharmacy.add(chckMainAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, -1));

        chkAlternativeAddress.setText("Secundaria");
        chkAlternativeAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAlternativeAddressActionPerformed(evt);
            }
        });
        pnlPharmacy.add(chkAlternativeAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, -1));

        lblAddressCheck.setForeground(new java.awt.Color(255, 0, 0));
        pnlPharmacy.add(lblAddressCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 50, -1));

        lblMedicineNameCheck.setForeground(new java.awt.Color(255, 0, 0));
        pnlPharmacy.add(lblMedicineNameCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        lblItemNumberCheck.setForeground(new java.awt.Color(255, 0, 0));
        pnlPharmacy.add(lblItemNumberCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        lblTitle.setText("Ingrese su pedido:");
        lblTitle.setToolTipText("");

        btnConfirm.setText("Confirmar");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(pnlPharmacy, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirm)
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlPharmacy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConfirm)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbtnProvider1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnProvider1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnProvider1ActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        System.out.println("Se ha pulsado el boton confirmar");
        System.out.println("Empezando validación...");
        if(validateForm()) {

                PharmacyItem item = new PharmacyItem();
                item.setNameMedicine(txtMedicineName.getText());
                item.setTypeMedicine(cmbTypeMedicine.getSelectedItem().toString());
                item.setItemNumber(Integer.parseInt(txtNumberItem.getValue().toString()));
                item.setProviderName(getSelectedProvider());

                String finalAddress = ""; 	
                if(chkAlternativeAddress.isSelected()) {
                        finalAddress += "Calle de la Rosa n. 28 ";
                        if(chckMainAddress.isSelected()) 
                                finalAddress += " y\n";	

                }

                if(chckMainAddress.isSelected()) {
                        finalAddress += "Calle Alcazabilla n. 3. ";
                }

                item.setAddress(finalAddress);

                System.out.println("Validación exitosa... ");
                ItemResponse responseForm = new ItemResponse(item);
                responseForm.setVisible(true);
                


        }else {
                System.out.println("Aún existen pendientes revisar los campos...");
        }
				
        validateForm();
        
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void txtMedicineNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedicineNameKeyReleased
        isValidateMedicineName();
    }//GEN-LAST:event_txtMedicineNameKeyReleased

    private void txtNumberItemStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtNumberItemStateChanged
        // TODO add your handling code here:
        isValidItemNumbers();
    }//GEN-LAST:event_txtNumberItemStateChanged

    private void chckMainAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckMainAddressActionPerformed
        // TODO add your handling code here:
        isValidAddress();
    }//GEN-LAST:event_chckMainAddressActionPerformed

    private void chkAlternativeAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAlternativeAddressActionPerformed
        // TODO add your handling code here:
        isValidAddress();
    }//GEN-LAST:event_chkAlternativeAddressActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PharmacyWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PharmacyWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PharmacyWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PharmacyWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PharmacyWindows().setVisible(true);
            }
        });
    }

    /***
    * Método para validar todos los campos del formulario
    */
    public boolean validateForm() {

           //Validacion campo de nombre de medicina
           if(isValidateMedicineName() && isValidItemNumbers() && isValidAddress()) {
                   return true;
           }
           else {
                   return false;
           }

   }

   public boolean isValidateMedicineName() {

           boolean isValid = true;
           if(txtMedicineName.getText().isEmpty()) {
                   isValid = false;
                   lblMedicineNameCheck.setToolTipText("El campo no puede estar vacío");
                   lblMedicineNameCheck.setText("Error");
           }else {
                   lblMedicineNameCheck.setToolTipText("");
                   lblMedicineNameCheck.setText("");
           }
           return isValid;
   }

   public boolean isValidItemNumbers() {

           boolean isValid = true;
           if(Integer.parseInt(txtNumberItem.getValue().toString()) <= 0 ) {
                   isValid = false;
                   lblItemNumberCheck.setToolTipText("El campo no puede estar vacío o ser menor a 0");
                   lblItemNumberCheck.setText("Error");
           }else {
                   lblItemNumberCheck.setToolTipText("");
                   lblItemNumberCheck.setText("");
           }
           return isValid;
   }

   public boolean isValidAddress() {

           boolean isValid = true;
           if(chkAlternativeAddress.isSelected() || chckMainAddress.isSelected()) {
                   lblAddressCheck.setToolTipText("");
                   lblAddressCheck.setText("");
           }else {
                   lblAddressCheck.setToolTipText("El campo no puede estar vacío");
                   lblAddressCheck.setText("Error");
                   isValid = false;
           }
           return isValid;
   }

   public String getSelectedProvider() {

           if(rdbtnProvider1.isSelected())
                   return rdbtnProvider1.getText();
           else if (rdbtProvider2.isSelected())
                   return rdbtProvider2.getText();
           else if (rdbtnProvider3.isSelected())
                   return rdbtnProvider3.getText();
           else 
                   return "No se ha seleccionado proveedor";
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.ButtonGroup btnGroupProviders;
    private javax.swing.JCheckBox chckMainAddress;
    private javax.swing.JCheckBox chkAlternativeAddress;
    private javax.swing.JComboBox<String> cmbTypeMedicine;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAddressCheck;
    private javax.swing.JLabel lblItemNumber;
    private javax.swing.JLabel lblItemNumberCheck;
    private javax.swing.JLabel lblMedicineName;
    private javax.swing.JLabel lblMedicineNameCheck;
    private javax.swing.JLabel lblProvider;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTypeMedicine;
    private javax.swing.JPanel pnlPharmacy;
    private javax.swing.JRadioButton rdbtProvider2;
    private javax.swing.JRadioButton rdbtnProvider1;
    private javax.swing.JRadioButton rdbtnProvider3;
    private javax.swing.JTextField txtMedicineName;
    private javax.swing.JSpinner txtNumberItem;
    // End of variables declaration//GEN-END:variables
}
